### ISSUE TITLE
FYI and thanks

### ISSUE THREAD

**Issue by alphapapa** [tali713/esxml#17]
Hi there @wasamasa ,

Just wanted to say thanks for `esxml-query`, I'm using it for this (WIP, just started), and it works great!

https://github.com/alphapapa/org-books

**Comment by wasamasa** [comment]
Glad it works for other people than myself!  If you have suggestions how to make the API (particularly the DOM accessors) more convenient, go ahead.

**Comment by alphapapa** [comment]
Thanks.  So far they seem to be great.  It would be interesting if there were a lispy way to do it, rather than in strings, but on the other hand, this is consistent with existing tools, so it probably makes the most sense.

**Comment by wasamasa** [comment]
I've considered a lispy DSL, but found it hard to design one with the same expressive power while being easy to type.  There's several competing projects going that route, but I found none of them to have a comparable feature set.  Here's my list:

- https://github.com/zweifisch/enlive
- https://github.com/AdamNiederer/elquery

**Comment by alphapapa** [comment]
I agree, and without reader macros it's even harder.  There *is* an Emacs reader macro package, but it's probably not something one would want to use in a serious package.  I hope elisp gets reader macros someday.  :)

**Comment by alphapapa** [comment]
BTW, I've put up a list of XML/HTML-related libraries here: https://alphapapa.github.io/emacs-package-dev-handbook/  Feel free to contribute anything you think would be helpful.  :)

**Comment by wasamasa** [comment]
I'd add https://github.com/volrath/treepy.el as a general-purpose way of tree traversal, I've used it for a prototype of esxml-query and later rewrote it to be dependency-free.

**Comment by alphapapa** [comment]
Good idea, thanks.
