### ISSUE TITLE
tali713 is missing from #emacs

### ISSUE THREAD

**Issue by mromyers** [tali713/esxml#19]
I'd provide a PR, but I'm not actually sure how to fix this one. Hopefully it will get resolved eventually.

**Comment by wasamasa** [comment]
I'm not sure how this is esxml-related.  In case you're worrying about the bus factor, I still have commit access and made use of it recently for `esxml-query.el`.  Why not send him an email and report in here if you ever get a response?

**Comment by mromyers** [comment]
It's not, at all. It was a joke I think I misjudged. Apologies.
