### ISSUE TITLE
Comment tags

### ISSUE THREAD

**Issue by guraltsev** [tali713/esxml#30]
Both xml and html define comment tags to be of the form 
```
<!--this is a comment-->
```
libxml converts comment tags to tags called `comment`. Then, when exporting, these get rendered as 
```
<comment>this is a comment</comment>
```
I think this is a bug.

**Comment by wasamasa** [comment]
Yes it is. I'll have to look into how to tackle this properly. Probably in `esxml--to-xml-recursive` and maybe `pp-esxml-to-xml`.

**Comment by tali713** [comment]
If the problem (as I understand it) is that libxml has an internal tag named comment, the simplest solution is indeed to update those two core functions to use pcase, rather than pcase-let, and special case that tag.

**Comment by wasamasa** [comment]
Good to see you're alive. I've updated a bit more than that and now the surrounding cond/if is replaced with pcase, too.

@guraltsev Could you please confirm it's fixed now?

**Comment by guraltsev** [comment]
Hello everyone. Thank you so much for the swift response. I confirm that it works perfectly now.
